# http://docs.travis-ci.com/user/getting-started/#PHP
# http://docs.travis-ci.com/user/languages/php/
language: php
php:
  - 5.5
  - 5.4
  - hhvm
# http://docs.travis-ci.com/user/database-setup/#MySQL
before_script:
  - mysql --user=root -e 'create database rcps_accounts;'
# ^- creates the database you use for testing in
  - mysql --init-command='use rcps_accounts;' < sql/schema.sql
  - mysql --init-command='use rcps_accounts;' < sql/base_setup.sql

# MySQL on Travis CI is started on boot, binds to 127.0.0.1 and requires
#  authentication. You can connect using the username "travis" or "root"
#  and a blank password. Note that the "travis" user does not have full
#  MySQL privileges that the "root" user does.

# Also, validate this after changing using http://yaml.travis-ci.org/

# From: https://github.com/travis-ci/travis-ci-php-example/blob/master/.travis.yml
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml --coverage-text
